# Generated by Django 5.0.1 on 2024-02-27 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='apartment')),
                ('description', models.TextField()),
                ('dishwasher', models.BooleanField()),
                ('sublet', models.BooleanField()),
                ('rent', models.IntegerField()),
                ('move_in_date', models.DateField()),
                ('lease_length', models.CharField(max_length=50)),
                ('pets_allowed', models.BooleanField()),
                ('num_beds', models.IntegerField()),
                ('num_baths', models.IntegerField()),
                ('num_sqr_ft', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textswap.user')),
            ],
        ),
    ]
