# Generated by Django 5.0.1 on 2024-04-05 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
