# Generated by Django 4.1.7 on 2024-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0003_user_is_landlord_user_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='washer',
            field=models.BooleanField(default=False),
        ),
    ]
