# Generated by Django 5.0.1 on 2024-04-02 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0005_rename_washer_apartment_washer_dryer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.TimeField()),
                ('content', models.TextField()),
                ('user1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='textswap.user')),
                ('user2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='textswap.user')),
            ],
        ),
    ]
