# Generated by Django 5.0.1 on 2024-04-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='textswap.user'),
        ),
    ]
