# Generated by Django 5.0.1 on 2024-04-02 19:55

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0008_alter_message_user1_id_alter_message_user2_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
