# Generated by Django 5.0.1 on 2024-04-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0010_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='parent_user',
        ),
    ]
