# Generated by Django 5.0.1 on 2024-04-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0011_rename_user_id_user_parent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
