version: '3.4'

volumes:
  django-gen:
  django-socket:
  postgres-data:
  postgres-socket:

services:
  django:
    build: "."
    command: uvicorn djangoproject.asgi:application --host 0.0.0.0 --port 8000 --reload
    environment:
      - DJANGO_SETTINGS_MODULE=djangoproject.settings
      - DJANGO_DEBUG
      - DJANGO_PUBLIC_HOSTNAME
      - DJANGO_SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    volumes:
      - "./django:/usr/src/django"
      - "django-socket:/var/www/uwsgi"
      - "django-gen:/gen"
      - "postgres-socket:/var/run/postgresql"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - "django-gen:/usr/share/nginx/html/static:ro"
    ports:
      - "80:80"
    depends_on:
      - django
  postgres:
    image: postgres:16.1
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "postgres-socket:/var/run/postgresql"
      - "./postgres_files:/postgres_files"
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
