# Generated by Django 4.2.11 on 2024-04-17 21:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import textswap.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('dishwasher', models.BooleanField()),
                ('washer_dryer', models.BooleanField(default=False)),
                ('sublet', models.BooleanField()),
                ('rent', models.IntegerField()),
                ('move_in_date', models.DateField()),
                ('lease_length', models.CharField(max_length=50)),
                ('pets_allowed', models.BooleanField()),
                ('num_beds', models.IntegerField()),
                ('num_baths', models.IntegerField()),
                ('num_sqr_ft', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_landlord', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('parent_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(default=None, max_length=100)),
                ('photo', models.ImageField(upload_to=textswap.models.get_upload_path)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textswap.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('user1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('user2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textswap.user'),
        ),
    ]
