# Generated by Django 4.2.11 on 2024-04-17 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
