# Generated by Django 4.2.11 on 2024-04-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0003_alter_apartment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='address',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='lease_length',
            field=models.CharField(),
        ),
    ]
