# Generated by Django 5.0.1 on 2024-04-05 21:14

import textswap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0003_alter_apartment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='photo_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='photo',
            field=models.ImageField(upload_to=textswap.models.get_upload_path),
        ),
    ]
