# Generated by Django 4.2.11 on 2024-04-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0004_alter_apartment_address_alter_apartment_lease_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(default=None),
        ),
    ]
