# Generated by Django 5.0.6 on 2024-06-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textswap', '0007_rename_user2_id_message_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
